// <auto-generated />
using System;
using CodeFirstSetup.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CodeFirstSetup.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210821124340_Initial4")]
    partial class Initial4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CodeFirstSetup.Data.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("HasRadio")
                        .HasColumnType("bit");

                    b.Property<int?>("Manufacturerid")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RegNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Manufacturerid");

                    b.ToTable("car");
                });

            modelBuilder.Entity("CodeFirstSetup.Data.Manufacturer", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("manufacturers");
                });

            modelBuilder.Entity("CodeFirstSetup.Data.Truck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("LoadVolumeKvm")
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.Property<int?>("Manufactureid")
                        .HasColumnType("int");

                    b.Property<string>("RegNumber")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.HasKey("Id");

                    b.HasIndex("Manufactureid");

                    b.ToTable("truck");
                });

            modelBuilder.Entity("CodeFirstSetup.Data.Car", b =>
                {
                    b.HasOne("CodeFirstSetup.Data.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("Manufacturerid");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("CodeFirstSetup.Data.Truck", b =>
                {
                    b.HasOne("CodeFirstSetup.Data.Manufacturer", "Manufacture")
                        .WithMany()
                        .HasForeignKey("Manufactureid");

                    b.Navigation("Manufacture");
                });
#pragma warning restore 612, 618
        }
    }
}
